### ISSUE TITLE
mvn qulice:check -Pqulice founds violations in file headers

### ISSUE THREAD

**Issue by RomanKisilenko** [jcabi/jcabi-manifests#16] opened 2015-01-13 12:40 UTC
```
[ERROR] /src/main/java/com/jcabi/manifests/ClasspathMfs.java[2]: Line does not match expected header line of ' * BSD License'. (HeaderCheck)
```
The issue is similar to https://github.com/jcabi/jcabi-email/issues/11

**Comment by yegor256** [comment] 2015-01-13 14:43
@RomanKisilenko how can I reproduce it?

**Comment by RomanKisilenko** [comment] 2015-01-13 15:05
The issue is reproducible for me by executing
```
mvn qulice:check -Pqulice
```

**Comment by dmarkov** [comment] 2015-01-14 13:23
this task will get someone's attention soon

**Comment by dmarkov** [comment] 2015-01-14 14:02
@maurezen it's in your hands now, please proceed

**Comment by maurezen** [comment] 2015-01-14 22:41
@dmarkov Created a pull request here #17

**Comment by maurezen** [comment] 2015-01-15 18:25
@dmarkov @yegor256 shouldn't there also be my account label on this ticket?

**Comment by dmarkov** [comment] 2015-01-19 13:24
@romankisilenko thanks for the report, I topped your acc for 15 mins, payment ID `50348224`

**Comment by maurezen** [comment] 2015-01-20 08:36
@RomanKisilenko pull request #17 merged to master, please close the issue.

**Comment by maurezen** [comment] 2015-01-21 11:41
@RomanKisilenko please close the issue.

**Comment by dmarkov** [comment] 2015-01-21 13:03
once `16-4036a3b3` puzzle is resolved, this ticket will be complete

**Comment by RomanKisilenko** [comment] 2015-01-21 13:30
@dmarkov Should I close this issue now or should we wait?

**Comment by yegor256** [comment] 2015-01-21 13:41
@RomanKisilenko up to you. if you are happy with the current solution, close it. if the problem is not solved and still blocks you, keep it open

**Closed** 2015-01-21 14:02 UTC
Labels: 30 mins, @maurezen, bug, DEV

**Comment by dmarkov** [comment] 2015-01-23 09:55
@maurezen thanks, paid, **30 mins** to your account, payment ID is `50616213`; +30 added to your rating, at the moment it is: [+885](http://www.netbout.com/b/35102?open=rating)

**Comment by dmarkov** [comment] 2015-05-07 11:45
@romankisilenko the last puzzle `16-4036a3b3`/#20 solved
